server:
  port: 8001

spring:
  cloud:
    gateway:
      routes:
      - id: first-service
        uri: http://localhost:9091/
        predicates:
        - Path=/firstservice/**
      - id: second-service
        uri: http://localhost:9092/
        predicates:
        - Path=/secondservice/**

#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8000/eureka
      

  
      
#management:
# endpoints:
 #   web:
  #    exposure:
   #     include: health, info

#info:
 # app:
  #  info:Hello Actuators!

## Configuring info endpoint
#info:
#app:
#name: Spring Sample Application
#description: This is my first spring boot application
#version: 1.0.0